project_id = "muksyipqfiyjlffhuaqe"

[functions.yelp-chat]
verify_jwt = true

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[auth]
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.yelp-proxy]
verify_jwt = true

[functions.plan-start]
verify_jwt = true

[functions.restaurant-select]
verify_jwt = true

[functions.activity-select]
verify_jwt = true

[functions.itinerary-confirm]
verify_jwt = true

[functions.get-itineraries]
verify_jwt = true

[functions.submit-feedback]
verify_jwt = true

[functions.get-profile]
verify_jwt = true

[functions.update-profile]
verify_jwt = true
